### ISSUE TITLE
Some fields in the date picker checkout page are smaller than they should be 

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/StickyBooking#130]
Reported by: t@occsn.com
  
Reason for priority: Someone want this fixed real bad

## Steps to reproduce

1. Go to: https://app.getoccasion.com/xp/0_bti3sohfhjx5o-yhbq6w
2. Notice some of the text fields appear smaller than others.

## Expected behavior

All text fields should have the same size.

## Actual behavior

Different sizes.

## Notes

https://secure.helpscout.net/conversation/568732920/18176/?folderId=605057

**Comment by nicklandgrebe** [comment]
Fixed
