### ISSUE TITLE
Customer reporting booking issues

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/StickyBooking#148]
Reported by: aksh@occsn.com
  
Reason for priority: A few customers can't book

## Steps to reproduce

1. Login as merchant 544
2. Book a pizza party for any date

## Expected behavior

Customer should be able to enter CC details

## Actual behavior

Customers are calling the merchant saying they can't enter CC details.`

## Notes

https://secure.helpscout.net/conversation/638253732

**Comment by pelletencate** [comment]
Could not reproduce. Informed merchant on HS.
