### ISSUE TITLE
SF merchant can't update listings

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/StickyBooking#150]
Reported by: t@occsn.com
  
Reason for priority: Someone want this fixed real bad

## Steps to reproduce

SF merchant 1981 is unable to make changes to her listings 

## Expected behavior

Ability to update listings 

## Actual behavior

An error message

## Notes

https://secure.helpscout.net/conversation/662153626

**Comment by pelletencate** [comment]
Can't reproduce. Merchant informed.
