### ISSUE TITLE
Seperator, Heading and text attributes not implemented

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/StickyBooking#36]
<img width="790" alt="not implemented attribbutes" src="https://user-images.githubusercontent.com/209089/33096023-38373794-cecb-11e7-825c-11fde6a8baf3.png">

**Comment by marcd123** [comment]
Will check in with Nick on this one tomorrow. There was an error before when submitting orders that had non-answerable questions like lines and headings.

**Comment by kieranklaassen** [comment]
@marcd123 You can implement the three attributes and @nicklandgrebe will fix it on our end

**Comment by marcd123** [comment]
Great will fix

**Comment by marcd123** [comment]
HTML is implemented properly as far as I can test for now. Issue is that those View form controls are no longer included in order.answers().target()

Assigning this to Nick.

**Comment by marcd123** [comment]
@nicklandgrebe  just added you to this.

**Comment by marcd123** [comment]
![image](https://user-images.githubusercontent.com/9528376/33150986-9e7c4ea6-cf9b-11e7-9e55-9258bb928f49.png)


Just pushed a commit that includes this log statement on line 247. When you review the answer objects it logs, we don't get any line breaks or text/header items.
