### ISSUE TITLE
Showing inactive option in option list

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/StickyBooking#47]
![informational_questions_-_default_headers](https://user-images.githubusercontent.com/209089/33279722-3b753534-d365-11e7-8721-6fadeb2b1c8c.png)

**Comment by kieranklaassen** [comment]
https://app.getoccasion.com/xp/hncuxeeynbmx4lc5xyk18g

**Comment by nicklandgrebe** [comment]
Fixed
