### ISSUE TITLE
Product description not showing on XP page

### ISSUE THREAD

**Issue by aksh0925** [GetOccasion/StickyBooking#65]
Steps to recreate:
1. Login to Merchant ID 1570
2. Go to product - https://bookings.stickyfolios.com/products/43417
3. Under 'basic' tab - you will see description
4. Now go to https://bookings.stickyfolios.com/xp/xfsp112y
5. On the top-left - it says "Welcome to the online booking tool. This platform will allow you to schedule, book, & pay for your session."

Expected: In stead "Welcome to the online booking tool. This platform will allow you to schedule, book, & pay for your session." -- it should include the product description.

**Comment by nicklandgrebe** [comment]
Fixed
