### ISSUE TITLE
Dates not bookable are showing as available

### ISSUE THREAD

**Issue by aksh0925** [GetOccasion/StickyBooking#66]
Steps to reproduce:
1. Go here - https://bookings.stickyfolios.com/xp/dt5xfjv6
2. Click on "December 16"

Expected:
12/16 should not show as available because no timeslot are available that date.

Actual:
It shows 12/16 as available, on-click nothing happens.

**Comment by nicklandgrebe** [comment]
Can't reproduce, Dec 16th shows a timeslot at 11:00am
