### ISSUE TITLE
Payment is required on free pages

### ISSUE THREAD

**Issue by aksh0925** [GetOccasion/StickyBooking#67]
To recreate:
1. Login as 3809
2. Go to this product - https://app.getoccasion.com/products/71477#/admin
3. Change experience to "sticky_bookigns"
4. Preview the new experience

Expected:
Since this is a free listing, payment fields should be hidden.

Actual:
The payment fields still appear.

**Comment by nicklandgrebe** [comment]
The product provided is not free, according to the programmatic conditions:

1. No base price
2. No questions that can affect price

In this case #2 is invalid, as `Number of Non-Painters 0 x $0.00 = $0.00 (Max of 10)` is price modifying

I don't think this is a bug, the code itself shows no error.
