### ISSUE TITLE
Credit card fields do not show up in the new design

### ISSUE THREAD

**Issue by aksh0925** [GetOccasion/StickyBooking#74]
To replicate:
1. Go to merchant ID 2150
2. Switch this listing to new experience - https://app.getoccasion.com/products/40686#/admin
3. Preview and fill out all the information

Expected:
You should be allowed to enter credit card.

Actual:
Credit card fields are not showing up - https://www.dropbox.com/s/u206z15sqrwjlf1/Screenshot%202017-12-27%2017.50.42.png?dl=0

**Comment by kieranklaassen** [comment]
This is when you do not have a price when the form loads but shows the payment form when a price comes in

**Comment by kieranklaassen** [comment]
next release
