### ISSUE TITLE
Error when loading the new experience

### ISSUE THREAD

**Issue by aksh0925** [GetOccasion/StickyBooking#75]
To recreate:

1. Merchant ID 4265
2. Go to this listing - https://bookings.stickyfolios.com/products/106597
3. Change the checkout experience to the new experience
4. Preview

Expected:
The page should load

Actual:
Gives an error that no timeslots are available even though timeslots are attached.

**Comment by kieranklaassen** [comment]
To recreate locally:

This is so that the first time slot is in March and it loads the first month and has nothing else. We should check what the first time slot it.

**Comment by kieranklaassen** [comment]
next release
