### ISSUE TITLE
Cannot book free events

### ISSUE THREAD

**Issue by aksh0925** [GetOccasion/StickyBooking#85]
Steps to reproduce:
1. Book this https://bookings.stickyfolios.com/xp/xogd5t7jgzo8hrhqdmweig
2. Fill out al the information and submit booking

Expected:
Booking to go through

Actual:
It gives an error.

**Comment by kieranklaassen** [comment]
noty a bug, product contains attendee field

![stickyfolios_-_booking_page](https://user-images.githubusercontent.com/209089/35246082-0e2c41f6-ff8b-11e7-918d-ec7bf2c7e93a.png)
