### ISSUE TITLE
Redesign and find a new placement for CTA

### ISSUE THREAD

**Issue by aksh0925** [GetOccasion/StickyBooking#98]
User Stories:
1. As a merchant, I want a more generic CTA on the booking page design so it's not in English for my french customers.

**Comment by nicklandgrebe** [comment]
@kieranklaassen @aksh0925 

1. Is the CTA the first button to be clicked?
2. What is meant by "more generic?"
3. How does that definition apply in situations where french-speakers are using the product instead of english-speakers?

**Comment by aksh0925** [comment]
@nicklandgrebe we are waiting on UX design from StickyFolio on this -- will circle back when they give them to us.

**Comment by aksh0925** [comment]
[OXN - Booking Page Updates.zip](https://github.com/GetOccasion/StickyBooking/files/1872467/OXN.-.Booking.Page.Updates.zip)
